POST http://127.0.0.1:4999/uploadTest
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="element-name"
Content-Type: text/plain

Name
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./test-image.png
--WebAppBoundary--
